### ISSUE TITLE
Specific URL to fetch data for a particular orchestrator

### ISSUE THREAD

**Issue by prastut** [buidl-labs/livepeer-pricing-tool#4]
http://35.223.32.189:9000/priceHistory/{orchestrator_address}
should render the pricing chart for that orchestrator

This is not working at the moment. 

I used this as a sample : http://35.223.32.189:3000/priceHistory/0xe9e284277648fcdb09b8efc1832c73c09b5ecf59

**Comment by Saumay-Agrawal** [comment]
> http://35.223.32.189:9000/priceHistory/{orchestrator_address}
should render the pricing chart for that orchestrator

Just to be clear, you mean http://35.223.32.189:3000/priceHistory/{orchestrator_address} here right?

**Comment by prastut** [comment]
@Saumay-Agrawal 

> here right?

Yes. The feedback is more conceptual than actual semantics. As a user if I need to share a particular orchestrator pricing history with my friend, I will share a particular URL with them. This issue is references that problem and isolates what needs to be solved. 

Also end users don't care about port number. We might need to host the api and pricing tool on a domain as well.
